name: Manual Deploy Trigger

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the environment to deploy"
        required: true
        type: choice
        options:
          - dev
          - prod
      version:
        description: "Input the version to deploy"
        default: "v0.0.1"
        required: true
        type: string

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    permissions:
      actions: write # 添加此权限
    steps:
      - name: Trigger Libre Chat Deploy
        uses: actions/github-script@v6
        with:
          script: |
            const currentBranch = context.ref.replace('refs/heads/', '');
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'librechat-deploy.yml',
              ref: currentBranch,
              inputs: {
                environment: '${{ github.event.inputs.environment }}',
                version: '${{ github.event.inputs.version }}'
              }
            })
