# This is a basic workflow that is manually triggered
name: Libre Chat Deploy
run-name: Deploy to ${{ github.event.workflow_run.inputs.environment }} - Version ${{ github.event.workflow_run.inputs.version }}
# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_run:
    workflows:
      - "Manual Deploy Trigger" # 监听 librechat-manual-deploy.yml
      - "Tag Deploy Trigger" # 监听 librechat-tags-deploy.yml
    types:
      - completed

env:
  DOCKER_IMAGE_NAME_PREFIX: app-agent-librechat
  DEPLOY_ENV: ${{github.event.workflow_run.inputs.environment }}
  DEPLOY_VERSION: ${{github.event.workflow_run.inputs.version }}

jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set environment variables
        id: extractEnv
        shell: bash
        run: |
          echo "DEPLOY_ENV=${{github.event.workflow_run.inputs.environment }}" >> $GITHUB_ENV
          echo "DEPLOY_VERSION=${{github.event.workflow_run.inputs.version }}" >> $GITHUB_ENV
